import {
  BookOpen,
  NotebookText,
  ClipboardCheck,
  FileText,
  MessageSquareQuote,
  Laptop,
  BookMarked,
  Library,
  HelpCircle,
  FolderKanban,
  HeartPulse,
  Sunrise,
  BrainCircuit,
  Bike,
  PersonStanding,
  Salad,
  BedDouble,
  GlassWater,
  PenSquare,
  MonitorOff,
  Smile,
  Users,
  HandHelping,
  HeartHandshake,
  Ear,
  ShieldCheck,
  Landmark,
  UserX,
  MessageCircle,
  Sticker,
  UserCheck,
  Hourglass,
  ListTodo,
  Clock,
  CheckCircle2,
  CalendarCheck2,
  Tv,
  Smartphone,
  Award,
  Lock,
  Medal,
  ThumbsUp,
  FileCheck as FileCheckIcon,
  Recycle,
  Lightbulb,
  Palette,
  Pencil,
  PenTool,
  School,
  Keyboard,
  Puzzle,
  Mic,
  Church,
  BookUser,
  Quote,
  Book,
  ClipboardX,
  ChevronsRight,
  EarOff,
  MessageSquareX,
  FileX,
  BookX,
  FolderX,
  ShieldAlert,
  Bed,
  Moon,
  Pizza,
  Coffee,
  CloudDrizzle,
  Dumbbell,
  Frown,
  Flame,
  BatteryWarning,
  UserRoundX,
  MessageCircleOff,
  XCircle,
  Siren,
  CircleOff,
  UserRoundCog,
  MonitorPlay,
  Gamepad2,
  MailWarning,
  ServerCrash,
  ThumbsDown,
  Trash2,
  Angry,
  Grab,
  Bot,
  Drama,
  Sparkles,
  AlarmClockOff,
  UserMinus,
  DoorClosed,
  MousePointerClick,
  Waves,
  HeartOff,
  type LucideIcon,
} from 'lucide-react';

export interface Activity {
  name: string;
  score: number;
  category: string;
  icon: LucideIcon;
  type: 'Good' | 'Bad';
  requiresProof?: boolean;
  animation?: 'like' | 'trophy' | 'sad';
}

export const activityCategories: { name: string; icon: LucideIcon; type: 'Good' | 'Bad' }[] = [
  // Good
  { name: 'Academic & Learning', icon: BookOpen, type: 'Good' },
  { name: 'Well-being & Self-care', icon: HeartPulse, type: 'Good' },
  { name: 'Social & Emotional Health', icon: Users, type: 'Good' },
  { name: 'Digital & Time Management', icon: Hourglass, type: 'Good' },
  { name: 'Character & Responsibility', icon: Award, type: 'Good' },
  { name: 'Creative & Enrichment', icon: Palette, type: 'Good' },
  { name: 'Spiritual or Reflective', icon: Sparkles, type: 'Good' },
  // Bad
  { name: 'Academic Neglect', icon: BookX, type: 'Bad' },
  { name: 'Self-Neglect', icon: Frown, type: 'Bad' },
  { name: 'Negative Social Behavior', icon: UserRoundX, type: 'Bad' },
  { name: 'Poor Digital Habits', icon: MonitorPlay, type: 'Bad' },
  { name: 'Responsibility Issues', icon: ThumbsDown, type: 'Bad' },
];

export const activities: Activity[] = [
  // --- GOOD KARMA ---
  // Academic & Learning
  { name: 'Classes', score: 9, category: 'Academic & Learning', icon: School, type: 'Good', animation: 'like' },
  { name: 'Homework', score: 8, category: 'Academic & Learning', icon: ClipboardCheck, type: 'Good', requiresProof: true, animation: 'like' },
  { name: 'Test Prep', score: 8, category: 'Academic & Learning', icon: FileCheckIcon, type: 'Good', requiresProof: true, animation: 'trophy' },
  { name: 'Take Notes', score: 7, category: 'Academic & Learning', icon: NotebookText, type: 'Good', animation: 'like' },
  { name: 'Participate', score: 7, category: 'Academic & Learning', icon: MessageSquareQuote, type: 'Good', animation: 'like' },
  { name: 'Self-Study', score: 6, category: 'Academic & Learning', icon: Laptop, type: 'Good', animation: 'like' },
  { name: 'Read Books', score: 7, category: 'Academic & Learning', icon: BookMarked, type: 'Good', animation: 'like' },
  { name: 'Library', score: 6, category: 'Academic & Learning', icon: Library, type: 'Good', animation: 'like' },
  { name: 'Ask Qs', score: 8, category: 'Academic & Learning', icon: HelpCircle, type: 'Good', animation: 'like' },
  { name: 'Organize', score: 6, category: 'Academic & Learning', icon: FolderKanban, type: 'Good', animation: 'like' },

  // Well-being & Self-care
  { name: 'Wake Early', score: 7, category: 'Well-being & Self-care', icon: Sunrise, type: 'Good', animation: 'like' },
  { name: 'Meditate', score: 8, category: 'Well-being & Self-care', icon: BrainCircuit, type: 'Good', animation: 'like' },
  { name: 'Exercise', score: 8, category: 'Well-being & Self-care', icon: Bike, type: 'Good', animation: 'like' },
  { name: 'Hygiene', score: 6, category: 'Well-being & Self-care', icon: PersonStanding, type: 'Good', animation: 'like' },
  { name: 'Healthy Meal', score: 6, category: 'Well-being & Self-care', icon: Salad, type: 'Good', animation: 'like' },
  { name: 'Good Sleep', score: 7, category: 'Well-being & Self-care', icon: BedDouble, type: 'Good', animation: 'like' },
  { name: 'Hydrate', score: 5, category: 'Well-being & Self-care', icon: GlassWater, type: 'Good', animation: 'like' },
  { name: 'Journal', score: 8, category: 'Well-being & Self-care', icon: PenSquare, type: 'Good', animation: 'like' },
  { name: 'No Screen', score: 7, category: 'Well-being & Self-care', icon: MonitorOff, type: 'Good', animation: 'like' },
  { name: 'Gratitude', score: 8, category: 'Well-being & Self-care', icon: Smile, type: 'Good', animation: 'like' },

  // Social & Emotional Health
  { name: 'Help Classmate', score: 8, category: 'Social & Emotional Health', icon: HandHelping, type: 'Good', requiresProof: true, animation: 'like' },
  { name: 'Be Kind', score: 9, category: 'Social & Emotional Health', icon: HeartHandshake, type: 'Good', animation: 'like' },
  { name: 'Listen', score: 7, category: 'Social & Emotional Health', icon: Ear, type: 'Good', animation: 'like' },
  { name: 'Apologize', score: 8, category: 'Social & Emotional Health', icon: Sticker, type: 'Good', animation: 'like' },
  { name: 'Respect Space', score: 7, category: 'Social & Emotional Health', icon: ShieldCheck, type: 'Good', animation: 'like' },
  { name: 'No Gossip', score: 6, category: 'Social & Emotional Health', icon: MessageCircle, type: 'Good', animation: 'like' },
  { name: 'Family Time', score: 7, category: 'Social & Emotional Health', icon: Users, type: 'Good', animation: 'like' },
  { name: 'Volunteer', score: 9, category: 'Social & Emotional Health', icon: Landmark, type: 'Good', requiresProof: true, animation: 'trophy' },
  { name: 'Be Polite', score: 8, category: 'Social & Emotional Health', icon: UserCheck, type: 'Good', animation: 'like' },
  { name: 'Resist Peer Pressure', score: 7, category: 'Social & Emotional Health', icon: UserX, type: 'Good', animation: 'like' },
  
  // Digital & Time Management
  { name: 'No Delay', score: 8, category: 'Digital & Time Management', icon: CheckCircle2, type: 'Good', animation: 'like' },
  { name: 'Log Off', score: 7, category: 'Digital & Time Management', icon: Smartphone, type: 'Good', animation: 'like' },
  { name: 'Use Tools', score: 6, category: 'Digital & Time Management', icon: ListTodo, type: 'Good', animation: 'like' },
  { name: 'Schedule', score: 7, category: 'Digital & Time Management', icon: CalendarCheck2, type: 'Good', animation: 'like' },
  { name: 'On Time', score: 8, category: 'Digital & Time Management', icon: Clock, type: 'Good', animation: 'like' },
  { name: 'Limit TV', score: 6, category: 'Digital & Time Management', icon: Tv, type: 'Good', animation: 'like' },

  // Character & Responsibility
  { name: 'Keep Promise', score: 8, category: 'Character & Responsibility', icon: Medal, type: 'Good', animation: 'like' },
  { name: 'Take Action', score: 9, category: 'Character & Responsibility', icon: ThumbsUp, type: 'Good', animation: 'like' },
  { name: 'Do Chores', score: 6, category: 'Character & Responsibility', icon: FileCheckIcon, type: 'Good', requiresProof: true, animation: 'like' },
  { name: 'Stand Up', score: 9, category: 'Character & Responsibility', icon: ShieldCheck, type: 'Good', animation: 'trophy' },
  { name: 'Be Honest', score: 10, category: 'Character & Responsibility', icon: Lock, type: 'Good', animation: 'trophy' },
  { name: 'Recycle', score: 6, category: 'Character & Responsibility', icon: Recycle, type: 'Good', animation: 'like' },
  { name: 'Stay Calm', score: 7, category: 'Character & Responsibility', icon: Lightbulb, type: 'Good', animation: 'like' },

  // Creative & Enrichment
  { name: 'Hobby', score: 7, category: 'Creative & Enrichment', icon: PenTool, type: 'Good', animation: 'like' },
  { name: 'Write', score: 6, category: 'Creative & Enrichment', icon: Pencil, type: 'Good', animation: 'like' },
  { name: 'Extra Fun', score: 7, 'category': 'Creative & Enrichment', icon: Puzzle, type: 'Good', animation: 'like' },
  { name: 'New Skill', score: 8, 'category': 'Creative & Enrichment', icon: Keyboard, type: 'Good', animation: 'like' },
  { name: 'Music', score: 7, category: 'Creative & Enrichment', icon: Mic, type: 'Good', animation: 'like' },

  // Spiritual or Reflective
  { name: 'Reflect', score: 8, category: 'Spiritual or Reflective', icon: Church, type: 'Good', animation: 'like' },
  { name: 'Quiet Time', score: 6, category: 'Spiritual or Reflective', icon: BookUser, type: 'Good', animation: 'like' },
  { name: 'Review Actions', score: 7, category: 'Spiritual or Reflective', icon: Book, type: 'Good', animation: 'like' },
  { name: 'Read Stories', score: 6, category: 'Spiritual or Reflective', icon: Quote, type: 'Good', animation: 'like' },

  // --- BAD KARMA ---
  { name: 'Skip Class', score: -9, category: 'Academic Neglect', icon: School, type: 'Bad', animation: 'sad' },
  { name: 'Procrastinated', score: -7, category: 'Academic Neglect', icon: Hourglass, type: 'Bad', animation: 'sad' },
  { name: 'Academic Dishonesty', score: -10, category: 'Academic Neglect', icon: BookX, type: 'Bad', animation: 'sad' },
  { name: 'Lost Focus in Class', score: -6, category: 'Academic Neglect', icon: EarOff, type: 'Bad', animation: 'sad' },
  { name: 'Refused Help', score: -5, category: 'Academic Neglect', icon: MessageSquareX, type: 'Bad', animation: 'sad' },
  { name: 'Skipped Note-taking', score: -5, category: 'Academic Neglect', icon: FileX, type: 'Bad', animation: 'sad' },
  { name: 'Unprepared', score: -8, category: 'Academic Neglect', icon: ClipboardX, type: 'Bad', animation: 'sad' },
  { name: 'Was Disorganized', score: -4, category: 'Academic Neglect', icon: FolderX, type: 'Bad', animation: 'sad' },
  { name: 'Blamed Others', score: -6, category: 'Academic Neglect', icon: UserRoundX, type: 'Bad', animation: 'sad' },
  { name: 'Overslept', score: -5, category: 'Self-Neglect', icon: AlarmClockOff, type: 'Bad', animation: 'sad' },
  { name: 'All Nighter', score: -7, category: 'Self-Neglect', icon: Moon, type: 'Bad', animation: 'sad' },
  { name: 'Ate Junk Food', score: -4, category: 'Self-Neglect', icon: Pizza, type: 'Bad', animation: 'sad' },
  { name: 'Skipped Meals', score: -6, category: 'Self-Neglect', icon: Coffee, type: 'Bad', animation: 'sad' },
  { name: 'Poor Hygiene', score: -6, category: 'Self-Neglect', icon: CloudDrizzle, type: 'Bad', animation: 'sad' },
  { name: 'Was Inactive', score: -4, category: 'Self-Neglect', icon: Bed, type: 'Bad', animation: 'sad' },
  { name: 'Felt Moody', score: -7, category: 'Self-Neglect', icon: Frown, type: 'Bad', animation: 'sad' },
  { name: 'Felt Stressed', score: -6, category: 'Self-Neglect', icon: Flame, type: 'Bad', animation: 'sad' },
  { name: 'Felt Burnt Out', score: -8, category: 'Self-Neglect', icon: BatteryWarning, type: 'Bad', animation: 'sad' },
  { name: 'Bullied Someone', score: -9, category: 'Negative Social Behavior', icon: UserRoundX, type: 'Bad', animation: 'sad' },
  { name: 'Gossiped', score: -6, category: 'Negative Social Behavior', icon: MessageCircleOff, type: 'Bad', animation: 'sad' },
  { name: 'Ignored Someone', score: -8, category: 'Negative Social Behavior', icon: UserMinus, type: 'Bad', animation: 'sad' },
  { name: 'Was Argumentative', score: -7, category: 'Negative Social Behavior', icon: Siren, type: 'Bad', animation: 'sad' },
  { name: 'Was Rude', score: -8, category: 'Negative Social Behavior', icon: Angry, type: 'Bad', animation: 'sad' },
  { name: 'Was Disruptive', score: -7, category: 'Negative Social Behavior', icon: Drama, type: 'Bad', animation: 'sad' },
  { name: 'Used Sarcasm', score: -6, category: 'Negative Social Behavior', icon: Bot, type: 'Bad', animation: 'sad' },
  { name: 'Self-Isolated', score: -5, category: 'Negative Social Behavior', icon: DoorClosed, type: 'Bad', animation: 'sad' },
  { name: 'Excessive Screen Time', score: -6, category: 'Poor Digital Habits', icon: Smartphone, type: 'Bad', animation: 'sad' },
  { name: 'Mindless Scrolling', score: -8, category: 'Poor Digital Habits', icon: MousePointerClick, type: 'Bad', animation: 'sad' },
  { name: 'Excessive Gaming', score: -6, category: 'Poor Digital Habits', icon: Gamepad2, type: 'Bad', animation: 'sad' },
  { name: 'Ignored Digital Tasks', score: -5, category: 'Poor Digital Habits', icon: MailWarning, type: 'Bad', animation: 'sad' },
  { name: 'Distracted Online', score: -7, category: 'Poor Digital Habits', icon: Waves, type: 'Bad', animation: 'sad' },
  { name: 'Was Dishonest', score: -8, category: 'Responsibility Issues', icon: ThumbsDown, type: 'Bad', animation: 'sad' },
  { name: 'Broke a Promise', score: -7, category: 'Responsibility Issues', icon: FileX, type: 'Bad', animation: 'sad' },
  { name: 'Skipped Chores', score: -5, category: 'Responsibility Issues', icon: Trash2, type: 'Bad', animation: 'sad' },
  { name: 'Lacked Empathy', score: -8, category: 'Responsibility Issues', icon: HeartOff, type: 'Bad', animation: 'sad' },
  { name: 'Mocked Others', score: -7, category: 'Responsibility Issues', icon: Angry, type: 'Bad', animation: 'sad' },
  { name: 'Stole Something', score: -10, category: 'Responsibility Issues', icon: Grab, type: 'Bad', animation: 'sad' },
];

export const goodKarmaActivities = activities.filter(a => a.type === 'Good');
export const badKarmaActivities = activities.filter(a => a.type === 'Bad');
