import {
  BookOpen,
  NotebookText,
  ClipboardCheck,
  FileText,
  MessageSquareQuote,
  Laptop,
  BookMarked,
  Library,
  HelpCircle,
  FolderKanban,
  HeartPulse,
  Sunrise,
  BrainCircuit,
  Bike,
  PersonStanding,
  Salad,
  BedDouble,
  GlassWater,
  PenSquare,
  MonitorOff,
  Smile,
  Users,
  HandHelping,
  HeartHandshake,
  Ear,
  ShieldCheck,
  Landmark,
  UserX,
  MessageCircle,
  Sticker,
  UserCheck,
  Hourglass,
  ListTodo,
  Clock,
  CheckCircle2,
  CalendarCheck2,
  Tv,
  Smartphone,
  Award,
  Lock,
  Medal,
  ThumbsUp,
  FileCheck as FileCheckIcon,
  Recycle,
  Lightbulb,
  Palette,
  Pencil,
  PenTool,
  School,
  Keyboard,
  Puzzle,
  Mic,
  Church,
  BookUser,
  Quote,
  Book,
  ClipboardX,
  ChevronsRight,
  EarOff,
  MessageSquareX,
  FileX,
  BookX,
  FolderX,
  ShieldAlert,
  Bed,
  Moon,
  Pizza,
  Coffee,
  CloudDrizzle,
  Dumbbell,
  Frown,
  Flame,
  BatteryWarning,
  UserRoundX,
  MessageCircleOff,
  XCircle,
  UserCog,
  Siren,
  CircleOff,
  UserRoundCog,
  MonitorPlay,
  Gamepad2,
  Newspaper,
  MailWarning,
  ServerCrash,
  ThumbsDown,
  Trash2,
  Angry,
  Grab,
  Bot,
  Drama,
  Sparkles,
  type LucideIcon,
} from 'lucide-react';

export interface Activity {
  name: string;
  score: number;
  category: string;
  icon: LucideIcon;
  type: 'Good' | 'Bad';
}

export const activityCategories: { name: string; icon: LucideIcon; type: 'Good' | 'Bad' }[] = [
  // Good
  { name: 'Academic & Learning', icon: BookOpen, type: 'Good' },
  { name: 'Well-being & Self-care', icon: HeartPulse, type: 'Good' },
  { name: 'Social & Emotional Health', icon: Users, type: 'Good' },
  { name: 'Digital & Time Management', icon: Hourglass, type: 'Good' },
  { name: 'Character & Responsibility', icon: Award, type: 'Good' },
  { name: 'Creative & Enrichment', icon: Palette, type: 'Good' },
  { name: 'Spiritual or Reflective', icon: Sparkles, type: 'Good' },
  // Bad
  { name: 'Academic Neglect', icon: BookX, type: 'Bad' },
  { name: 'Self-Neglect', icon: Frown, type: 'Bad' },
  { name: 'Negative Social Behavior', icon: UserRoundX, type: 'Bad' },
  { name: 'Poor Digital Habits', icon: MonitorPlay, type: 'Bad' },
  { name: 'Responsibility Issues', icon: ThumbsDown, type: 'Bad' },
];

export const activities: Activity[] = [
  // --- GOOD KARMA ---
  // Academic & Learning
  { name: 'Classes', score: 9, category: 'Academic & Learning', icon: School, type: 'Good' },
  { name: 'Homework', score: 8, category: 'Academic & Learning', icon: ClipboardCheck, type: 'Good' },
  { name: 'Test Prep', score: 8, category: 'Academic & Learning', icon: FileCheckIcon, type: 'Good' },
  { name: 'Take Notes', score: 7, category: 'Academic & Learning', icon: NotebookText, type: 'Good' },
  { name: 'Participate', score: 7, category: 'Academic & Learning', icon: MessageSquareQuote, type: 'Good' },
  { name: 'Self-Study', score: 6, category: 'Academic & Learning', icon: Laptop, type: 'Good' },
  { name: 'Read Books', score: 7, category: 'Academic & Learning', icon: BookMarked, type: 'Good' },
  { name: 'Library', score: 6, category: 'Academic & Learning', icon: Library, type: 'Good' },
  { name: 'Ask Qs', score: 8, category: 'Academic & Learning', icon: HelpCircle, type: 'Good' },
  { name: 'Organize', score: 6, category: 'Academic & Learning', icon: FolderKanban, type: 'Good' },

  // Well-being & Self-care
  { name: 'Wake Early', score: 7, category: 'Well-being & Self-care', icon: Sunrise, type: 'Good' },
  { name: 'Meditate', score: 8, category: 'Well-being & Self-care', icon: BrainCircuit, type: 'Good' },
  { name: 'Exercise', score: 8, category: 'Well-being & Self-care', icon: Bike, type: 'Good' },
  { name: 'Hygiene', score: 6, category: 'Well-being & Self-care', icon: PersonStanding, type: 'Good' },
  { name: 'Healthy Meal', score: 6, category: 'Well-being & Self-care', icon: Salad, type: 'Good' },
  { name: 'Good Sleep', score: 7, category: 'Well-being & Self-care', icon: BedDouble, type: 'Good' },
  { name: 'Hydrate', score: 5, category: 'Well-being & Self-care', icon: GlassWater, type: 'Good' },
  { name: 'Journal', score: 8, category: 'Well-being & Self-care', icon: PenSquare, type: 'Good' },
  { name: 'No Screen', score: 7, category: 'Well-being & Self-care', icon: MonitorOff, type: 'Good' },
  { name: 'Gratitude', score: 8, category: 'Well-being & Self-care', icon: Smile, type: 'Good' },

  // Social & Emotional Health
  { name: 'Help Classmate', score: 8, category: 'Social & Emotional Health', icon: HandHelping, type: 'Good' },
  { name: 'Be Kind', score: 9, category: 'Social & Emotional Health', icon: HeartHandshake, type: 'Good' },
  { name: 'Listen', score: 7, category: 'Social & Emotional Health', icon: Ear, type: 'Good' },
  { name: 'Apologize', score: 8, category: 'Social & Emotional Health', icon: Sticker, type: 'Good' },
  { name: 'Respect Space', score: 7, category: 'Social & Emotional Health', icon: ShieldCheck, type: 'Good' },
  { name: 'No Gossip', score: 6, category: 'Social & Emotional Health', icon: MessageCircle, type: 'Good' },
  { name: 'Family Time', score: 7, category: 'Social & Emotional Health', icon: Users, type: 'Good' },
  { name: 'Volunteer', score: 9, category: 'Social & Emotional Health', icon: Landmark, type: 'Good' },
  { name: 'Be Polite', score: 8, category: 'Social & Emotional Health', icon: UserCheck, type: 'Good' },
  { name: 'Resist Peer Pressure', score: 7, category: 'Social & Emotional Health', icon: UserX, type: 'Good' },
  
  // Digital & Time Management
  { name: 'No Delay', score: 8, category: 'Digital & Time Management', icon: CheckCircle2, type: 'Good' },
  { name: 'Log Off', score: 7, category: 'Digital & Time Management', icon: Smartphone, type: 'Good' },
  { name: 'Use Tools', score: 6, category: 'Digital & Time Management', icon: ListTodo, type: 'Good' },
  { name: 'Schedule', score: 7, category: 'Digital & Time Management', icon: CalendarCheck2, type: 'Good' },
  { name: 'On Time', score: 8, category: 'Digital & Time Management', icon: Clock, type: 'Good' },
  { name: 'Limit TV', score: 6, category: 'Digital & Time Management', icon: Tv, type: 'Good' },

  // Character & Responsibility
  { name: 'Keep Promise', score: 8, category: 'Character & Responsibility', icon: Medal, type: 'Good' },
  { name: 'Take Action', score: 9, category: 'Character & Responsibility', icon: ThumbsUp, type: 'Good' },
  { name: 'Do Chores', score: 6, category: 'Character & Responsibility', icon: FileCheckIcon, type: 'Good' },
  { name: 'Stand Up', score: 9, category: 'Character & Responsibility', icon: ShieldCheck, type: 'Good' },
  { name: 'Be Honest', score: 10, category: 'Character & Responsibility', icon: Lock, type: 'Good' },
  { name: 'Recycle', score: 6, category: 'Character & Responsibility', icon: Recycle, type: 'Good' },
  { name: 'Stay Calm', score: 7, category: 'Character & Responsibility', icon: Lightbulb, type: 'Good' },

  // Creative & Enrichment
  { name: 'Hobby', score: 7, category: 'Creative & Enrichment', icon: PenTool, type: 'Good' },
  { name: 'Write', score: 6, category: 'Creative & Enrichment', icon: Pencil, type: 'Good' },
  { name: 'Extra Fun', score: 7, 'category': 'Creative & Enrichment', icon: Puzzle, type: 'Good' },
  { name: 'New Skill', score: 8, 'category': 'Creative & Enrichment', icon: Keyboard, type: 'Good' },
  { name: 'Music', score: 7, category: 'Creative & Enrichment', icon: Mic, type: 'Good' },

  // Spiritual or Reflective
  { name: 'Reflect', score: 8, category: 'Spiritual or Reflective', icon: Church, type: 'Good' },
  { name: 'Quiet Time', score: 6, category: 'Spiritual or Reflective', icon: BookUser, type: 'Good' },
  { name: 'Review Actions', score: 7, category: 'Spiritual or Reflective', icon: Book, type: 'Good' },
  { name: 'Read Stories', score: 6, category: 'Spiritual or Reflective', icon: Quote, type: 'Good' },

  // --- BAD KARMA ---
  // Academic Neglect
  { name: 'Skip Class', score: -9, category: 'Academic Neglect', icon: School, type: 'Bad' },
  { name: 'No Homework', score: -7, category: 'Academic Neglect', icon: ClipboardX, type: 'Bad' },
  { name: 'Cheat', score: -10, category: 'Academic Neglect', icon: ChevronsRight, type: 'Bad' },
  { name: 'Zone Out', score: -6, category: 'Academic Neglect', icon: EarOff, type: 'Bad' },
  { name: 'Refuse', score: -5, category: 'Academic Neglect', icon: MessageSquareX, type: 'Bad' },
  { name: 'No Notes', score: -5, category: 'Academic Neglect', icon: FileX, type: 'Bad' },
  { name: 'No Prep', score: -8, category: 'Academic Neglect', icon: BookX, type: 'Bad' },
  { name: 'Lose Stuff', score: -4, category: 'Academic Neglect', icon: FolderX, type: 'Bad' },
  { name: 'Blame Game', score: -6, category: 'Academic Neglect', icon: ShieldAlert, type: 'Bad' },

  // Self-Neglect
  { name: 'Oversleep', score: -5, category: 'Self-Neglect', icon: Bed, type: 'Bad' },
  { name: 'All Nighter', score: -7, category: 'Self-Neglect', icon: Moon, type: 'Bad' },
  { name: 'Junk Food', score: -4, category: 'Self-Neglect', icon: Pizza, type: 'Bad' },
  { name: 'Skip Meals', score: -6, category: 'Self-Neglect', icon: Coffee, type: 'Bad' },
  { name: 'No Shower', score: -6, category: 'Self-Neglect', icon: CloudDrizzle, type: 'Bad' },
  { name: 'Lazy', score: -4, category: 'Self-Neglect', icon: Dumbbell, type: 'Bad' },
  { name: 'Ignore Feels', score: -7, category: 'Self-Neglect', icon: Frown, type: 'Bad' },
  { name: 'Stress', score: -6, category: 'Self-Neglect', icon: Flame, type: 'Bad' },
  { name: 'Burnout', score: -8, category: 'Self-Neglect', icon: BatteryWarning, type: 'Bad' },

  // Negative Social Behavior
  { name: 'Bully', score: -9, category: 'Negative Social Behavior', icon: UserRoundX, type: 'Bad' },
  { name: 'Gossip', score: -6, category: 'Negative Social Behavior', icon: MessageCircleOff, type: 'Bad' },
  { name: 'Ignore', score: -8, category: 'Negative Social Behavior', icon: UserCog, type: 'Bad' },
  { name: 'Argue', score: -7, category: 'Negative Social Behavior', icon: Siren, type: 'Bad' },
  { name: 'Rude', score: -8, category: 'Negative Social Behavior', icon: CircleOff, type: 'Bad' },
  { name: 'Disrupt', score: -7, category: 'Negative Social Behavior', icon: Drama, type: 'Bad' },
  { name: 'Sarcasm', score: -6, category: 'Negative Social Behavior', icon: Bot, type: 'Bad' },
  { name: 'Isolate', score: -5, category: 'Negative Social Behavior', icon: UserRoundCog, type: 'Bad' },

  // Poor Digital Habits
  { name: 'Phone Addict', score: -6, category: 'Poor Digital Habits', icon: Smartphone, type: 'Bad' },
  { name: 'Scroll', score: -6, category: 'Poor Digital Habits', icon: Newspaper, type: 'Bad' },
  { name: 'Bad Content', score: -8, category: 'Poor Digital Habits', icon: MonitorPlay, type: 'Bad' },
  { name: 'Game', score: -6, category: 'Poor Digital Habits', icon: Gamepad2, type: 'Bad' },
  { name: 'Ignore Mail', score: -5, category: 'Poor Digital Habits', icon: MailWarning, type: 'Bad' },
  { name: 'Web Surf', score: -7, category: 'Poor Digital Habits', icon: ServerCrash, type: 'Bad' },

  // Responsibility Issues
  { name: 'Lie', score: -8, category: 'Responsibility Issues', icon: ThumbsDown, type: 'Bad' },
  { name: 'Break Promise', score: -7, category: 'Responsibility Issues', icon: FileX, type: 'Bad' },
  { name: 'Skip Chores', score: -5, category: 'Responsibility Issues', icon: Trash2, type: 'Bad' },
  { name: 'Blame', score: -6, category: 'Responsibility Issues', icon: ShieldAlert, type: 'Bad' },
  { name: 'No Empathy', score: -8, category: 'Responsibility Issues', icon: Frown, type: 'Bad' },
  { name: 'Mock Others', score: -7, category: 'Responsibility Issues', icon: Angry, type: 'Bad' },
  { name: 'Steal', score: -10, category: 'Responsibility Issues', icon: Grab, type: 'Bad' },
];

export const goodKarmaActivities = activities.filter(a => a.type === 'Good');
export const badKarmaActivities = activities.filter(a => a.type === 'Bad');
