import {
  BookOpen,
  NotebookText,
  ClipboardCheck,
  FileText,
  MessageSquareQuote,
  Laptop,
  BookMarked,
  Library,
  HelpCircle,
  FolderKanban,
  HeartPulse,
  Sunrise,
  BrainCircuit,
  Bike,
  PersonStanding,
  Salad,
  BedDouble,
  GlassWater,
  PenSquare,
  MonitorOff,
  Smile,
  Users,
  HandHelping,
  HeartHandshake,
  Ear,
  ShieldCheck,
  Landmark,
  UserX,
  MessageCircle,
  Sticker,
  UserCheck,
  Hourglass,
  ListTodo,
  Clock,
  CheckCircle2,
  CalendarCheck2,
  Tv,
  Smartphone,
  Award,
  Lock,
  Medal,
  ThumbsUp,
  FileCheck as FileCheckIcon,
  Recycle,
  Lightbulb,
  Palette,
  Pencil,
  PenTool,
  School,
  Keyboard,
  Puzzle,
  Mic,
  Church,
  BookUser,
  Quote,
  Book,
  ClipboardX,
  ChevronsRight,
  EarOff,
  MessageSquareX,
  FileX,
  BookX,
  FolderX,
  ShieldAlert,
  Bed,
  Moon,
  Pizza,
  Coffee,
  CloudDrizzle,
  Dumbbell,
  Frown,
  Flame,
  BatteryWarning,
  UserRoundX,
  MessageCircleOff,
  XCircle,
  UserCog,
  Siren,
  CircleOff,
  UserRoundCog,
  MonitorPlay,
  Gamepad2,
  Newspaper,
  MailWarning,
  ServerCrash,
  ThumbsDown,
  Trash2,
  Angry,
  Grab,
  Bot,
  Drama,
  Sparkles,
  type LucideIcon,
} from 'lucide-react';

export interface Activity {
  name: string;
  score: number;
  category: string;
  icon: LucideIcon;
  type: 'Good' | 'Bad';
}

export const activityCategories: { name: string; icon: LucideIcon; type: 'Good' | 'Bad' }[] = [
  // Good
  { name: 'Academic & Learning', icon: BookOpen, type: 'Good' },
  { name: 'Well-being & Self-care', icon: HeartPulse, type: 'Good' },
  { name: 'Social & Emotional Health', icon: Users, type: 'Good' },
  { name: 'Digital & Time Management', icon: Hourglass, type: 'Good' },
  { name: 'Character & Responsibility', icon: Award, type: 'Good' },
  { name: 'Creative & Enrichment', icon: Palette, type: 'Good' },
  { name: 'Spiritual or Reflective', icon: Sparkles, type: 'Good' },
  // Bad
  { name: 'Academic Neglect', icon: BookX, type: 'Bad' },
  { name: 'Self-Neglect', icon: Frown, type: 'Bad' },
  { name: 'Negative Social Behavior', icon: UserRoundX, type: 'Bad' },
  { name: 'Poor Digital Habits', icon: MonitorPlay, type: 'Bad' },
  { name: 'Responsibility Issues', icon: ThumbsDown, type: 'Bad' },
];

export const activities: Activity[] = [
  // --- GOOD KARMA ---
  // Academic & Learning
  { name: 'Attending classes', score: 9, category: 'Academic & Learning', icon: School, type: 'Good' },
  { name: 'Completing homework', score: 8, category: 'Academic & Learning', icon: ClipboardCheck, type: 'Good' },
  { name: 'Preparing for tests', score: 8, category: 'Academic & Learning', icon: FileCheckIcon, type: 'Good' },
  { name: 'Taking study notes', score: 7, category: 'Academic & Learning', icon: NotebookText, type: 'Good' },
  { name: 'Participating in class', score: 7, category: 'Academic & Learning', icon: MessageSquareQuote, type: 'Good' },
  { name: 'Self-study/online learning', score: 6, category: 'Academic & Learning', icon: Laptop, type: 'Good' },
  { name: 'Reading educational books', score: 7, category: 'Academic & Learning', icon: BookMarked, type: 'Good' },
  { name: 'Visiting the library', score: 6, category: 'Academic & Learning', icon: Library, type: 'Good' },
  { name: 'Asking questions', score: 8, category: 'Academic & Learning', icon: HelpCircle, type: 'Good' },
  { name: 'Organizing materials', score: 6, category: 'Academic & Learning', icon: FolderKanban, type: 'Good' },

  // Well-being & Self-care
  { name: 'Waking up on time', score: 7, category: 'Well-being & Self-care', icon: Sunrise, type: 'Good' },
  { name: 'Mindfulness/meditation', score: 8, category: 'Well-being & Self-care', icon: BrainCircuit, type: 'Good' },
  { name: 'Exercising or yoga', score: 8, category: 'Well-being & Self-care', icon: Bike, type: 'Good' },
  { name: 'Personal hygiene', score: 6, category: 'Well-being & Self-care', icon: PersonStanding, type: 'Good' },
  { name: 'Eating nutritious meals', score: 6, category: 'Well-being & Self-care', icon: Salad, type: 'Good' },
  { name: 'Adequate sleep', score: 7, category: 'Well-being & Self-care', icon: BedDouble, type: 'Good' },
  { name: 'Drinking enough water', score: 5, category: 'Well-being & Self-care', icon: GlassWater, type: 'Good' },
  { name: 'Journaling', score: 8, category: 'Well-being & Self-care', icon: PenSquare, type: 'Good' },
  { name: 'Managing screen time', score: 7, category: 'Well-being & Self-care', icon: MonitorOff, type: 'Good' },
  { name: 'Practicing gratitude', score: 8, category: 'Well-being & Self-care', icon: Smile, type: 'Good' },

  // Social & Emotional Health
  { name: 'Helping a classmate', score: 8, category: 'Social & Emotional Health', icon: HandHelping, type: 'Good' },
  { name: 'Showing empathy', score: 9, category: 'Social & Emotional Health', icon: HeartHandshake, type: 'Good' },
  { name: 'Listening actively', score: 7, category: 'Social & Emotional Health', icon: Ear, type: 'Good' },
  { name: 'Apologizing for a mistake', score: 8, category: 'Social & Emotional Health', icon: Sticker, type: 'Good' },
  { name: 'Respecting boundaries', score: 7, category: 'Social & Emotional Health', icon: ShieldCheck, type: 'Good' },
  { name: 'Avoiding gossip', score: 6, category: 'Social & Emotional Health', icon: MessageCircle, type: 'Good' },
  { name: 'Spending time with family', score: 7, category: 'Social & Emotional Health', icon: Users, type: 'Good' },
  { name: 'Volunteering', score: 9, category: 'Social & Emotional Health', icon: Landmark, type: 'Good' },
  { name: 'Speaking politely', score: 8, category: 'Social & Emotional Health', icon: UserCheck, type: 'Good' },
  { name: 'Avoiding peer pressure', score: 7, category: 'Social & Emotional Health', icon: UserX, type: 'Good' },
  
  // Digital & Time Management
  { name: 'Avoiding procrastination', score: 8, category: 'Digital & Time Management', icon: CheckCircle2, type: 'Good' },
  { name: 'Logging off distractions', score: 7, category: 'Digital & Time Management', icon: Smartphone, type: 'Good' },
  { name: 'Using productivity tools', score: 6, category: 'Digital & Time Management', icon: ListTodo, type: 'Good' },
  { name: 'Following a schedule', score: 7, category: 'Digital & Time Management', icon: CalendarCheck2, type: 'Good' },
  { name: 'Completing tasks on time', score: 8, category: 'Digital & Time Management', icon: Clock, type: 'Good' },
  { name: 'Limiting entertainment', score: 6, category: 'Digital & Time Management', icon: Tv, type: 'Good' },

  // Character & Responsibility
  { name: 'Keeping promises', score: 8, category: 'Character & Responsibility', icon: Medal, type: 'Good' },
  { name: 'Taking accountability', score: 9, category: 'Character & Responsibility', icon: ThumbsUp, type: 'Good' },
  { name: 'Completing chores', score: 6, category: 'Character & Responsibility', icon: FileCheckIcon, type: 'Good' },
  { name: 'Standing up for right', score: 9, category: 'Character & Responsibility', icon: ShieldCheck, type: 'Good' },
  { name: 'Staying honest', score: 10, category: 'Character & Responsibility', icon: Lock, type: 'Good' },
  { name: 'Saving resources', score: 6, category: 'Character & Responsibility', icon: Recycle, type: 'Good' },
  { name: 'Managing anger', score: 7, category: 'Character & Responsibility', icon: Lightbulb, type: 'Good' },

  // Creative & Enrichment
  { name: 'Practicing a hobby', score: 7, category: 'Creative & Enrichment', icon: PenTool, type: 'Good' },
  { name: 'Writing creatively', score: 6, category: 'Creative & Enrichment', icon: Pencil, type: 'Good' },
  { name: 'Extracurriculars', score: 7, 'category': 'Creative & Enrichment', icon: Puzzle, type: 'Good' },
  { name: 'Learning a new skill', score: 8, 'category': 'Creative & Enrichment', icon: Keyboard, type: 'Good' },
  { name: 'Playing an instrument', score: 7, category: 'Creative & Enrichment', icon: Mic, type: 'Good' },

  // Spiritual or Reflective
  { name: 'Spiritual reflection', score: 8, category: 'Spiritual or Reflective', icon: Church, type: 'Good' },
  { name: 'Quiet time alone', score: 6, category: 'Spiritual or Reflective', icon: BookUser, type: 'Good' },
  { name: 'Reflecting on actions', score: 7, category: 'Spiritual or Reflective', icon: Book, type: 'Good' },
  { name: 'Reading moral stories', score: 6, category: 'Spiritual or Reflective', icon: Quote, type: 'Good' },

  // --- BAD KARMA ---
  // Academic Neglect
  { name: 'Skipping classes', score: -9, category: 'Academic Neglect', icon: School, type: 'Bad' },
  { name: 'Ignoring homework', score: -7, category: 'Academic Neglect', icon: ClipboardX, type: 'Bad' },
  { name: 'Cheating in tests', score: -10, category: 'Academic Neglect', icon: ChevronsRight, type: 'Bad' },
  { name: 'Not paying attention', score: -6, category: 'Academic Neglect', icon: EarOff, type: 'Bad' },
  { name: 'Refusing to participate', score: -5, category: 'Academic Neglect', icon: MessageSquareX, type: 'Bad' },
  { name: 'Not taking notes', score: -5, category: 'Academic Neglect', icon: FileX, type: 'Bad' },
  { name: 'Not preparing for exams', score: -8, category: 'Academic Neglect', icon: BookX, type: 'Bad' },
  { name: 'Losing study materials', score: -4, category: 'Academic Neglect', icon: FolderX, type: 'Bad' },
  { name: 'Blaming others for failure', score: -6, category: 'Academic Neglect', icon: ShieldAlert, type: 'Bad' },

  // Self-Neglect
  { name: 'Oversleeping', score: -5, category: 'Self-Neglect', icon: Bed, type: 'Bad' },
  { name: 'Staying up all night', score: -7, category: 'Self-Neglect', icon: Moon, type: 'Bad' },
  { name: 'Eating junk food', score: -4, category: 'Self-Neglect', icon: Pizza, type: 'Bad' },
  { name: 'Skipping meals', score: -6, category: 'Self-Neglect', icon: Coffee, type: 'Bad' },
  { name: 'Neglecting hygiene', score: -6, category: 'Self-Neglect', icon: CloudDrizzle, type: 'Bad' },
  { name: 'Avoiding exercise', score: -4, category: 'Self-Neglect', icon: Dumbbell, type: 'Bad' },
  { name: 'Ignoring emotions', score: -7, category: 'Self-Neglect', icon: Frown, type: 'Bad' },
  { name: 'Bottling up stress', score: -6, category: 'Self-Neglect', icon: Flame, type: 'Bad' },
  { name: 'Frequent burnout', score: -8, category: 'Self-Neglect', icon: BatteryWarning, type: 'Bad' },

  // Negative Social Behavior
  { name: 'Bullying or teasing', score: -9, category: 'Negative Social Behavior', icon: UserRoundX, type: 'Bad' },
  { name: 'Gossiping', score: -6, category: 'Negative Social Behavior', icon: MessageCircleOff, type: 'Bad' },
  { name: 'Ignoring someone in distress', score: -8, category: 'Negative Social Behavior', icon: UserCog, type: 'Bad' },
  { name: 'Arguing with peers/teachers', score: -7, category: 'Negative Social Behavior', icon: Siren, type: 'Bad' },
  { name: 'Using disrespectful language', score: -8, category: 'Negative Social Behavior', icon: CircleOff, type: 'Bad' },
  { name: 'Disrupting class', score: -7, category: 'Negative Social Behavior', icon: Drama, type: 'Bad' },
  { name: 'Being rude or sarcastic', score: -6, category: 'Negative Social Behavior', icon: Bot, type: 'Bad' },
  { name: 'Isolating oneself', score: -5, category: 'Negative Social Behavior', icon: UserRoundCog, type: 'Bad' },

  // Poor Digital Habits
  { name: 'Excessive phone usage', score: -6, category: 'Poor Digital Habits', icon: Smartphone, type: 'Bad' },
  { name: 'Addictive social media', score: -6, category: 'Poor Digital Habits', icon: Newspaper, type: 'Bad' },
  { name: 'Inappropriate content', score: -8, category: 'Poor Digital Habits', icon: MonitorPlay, type: 'Bad' },
  { name: 'Gaming during study', score: -6, category: 'Poor Digital Habits', icon: Gamepad2, type: 'Bad' },
  { name: 'Ignoring important emails', score: -5, category: 'Poor Digital Habits', icon: MailWarning, type: 'Bad' },
  { name: 'Online during class', score: -7, category: 'Poor Digital Habits', icon: ServerCrash, type: 'Bad' },

  // Responsibility Issues
  { name: 'Lying', score: -8, category: 'Responsibility Issues', icon: ThumbsDown, type: 'Bad' },
  { name: 'Breaking promises', score: -7, category: 'Responsibility Issues', icon: FileX, type: 'Bad' },
  { name: 'Avoiding chores', score: -5, category: 'Responsibility Issues', icon: Trash2, type: 'Bad' },
  { name: 'Blaming others', score: -6, category: 'Responsibility Issues', icon: ShieldAlert, type: 'Bad' },
  { name: 'Lack of empathy', score: -8, category: 'Responsibility Issues', icon: Frown, type: 'Bad' },
  { name: 'Making fun of others', score: -7, category: 'Responsibility Issues', icon: Angry, type: 'Bad' },
  { name: 'Stealing', score: -10, category: 'Responsibility Issues', icon: Grab, type: 'Bad' },
];

export const goodKarmaActivities = activities.filter(a => a.type === 'Good');
export const badKarmaActivities = activities.filter(a => a.type === 'Bad');
